### ISSUE TITLE
Update to dashy?

### ISSUE THREAD

**Issue by mbobbar** [BenoitAnastay/home-assistant-addons-repository#3]
Hey thanks for the fantastic repo!
Do you have any plans to update the dashy image to 3.1.1?

**Comment by BenoitAnastay** [comment]
I wasn't maintaining dashy, I thought no one cares.

But sure I can update it

**Comment by BenoitAnastay** [comment]
Updated to 3.1.1, please tell me if you encounter any issue

**Comment by mbobbar** [comment]
Yep noticed those are not quite right, thanks for looking into it

**Comment by BenoitAnastay** [comment]
I've fully rewrote the add-on and its now running well, I've released the update.

The first run might take time and display you an error message, you will just have to wait and refresh the page.

It seems that the building is unexpectedly long on low power devices

You'll also need to backup your settings manually before running the update

**Comment by mbobbar** [comment]
Hey, still having issues with startup and it appears to be pointed to a strange IP on port 4000 rather than the port specified in config.

 System: Home Assistant OS 12.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.0
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
yarn run v1.22.19
$ node server

Checking config file against schema...
✔️ Config file is valid, no issues found

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Welcome to Dashy! 🚀                                                      ┃
┃ Your new dashboard is now up and running at http://172.30.33.11:4000      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛



Using Dashy V-3.1.1. Update Check Complete
✅ Dashy is Up-to-Date

s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
cont-finish: info: running /etc/cont-finish.d/99-message.sh
/etc/cont-finish.d/99-message.sh: line 6: S6_STAGE2_EXITED: unbound variable
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh

-----------------------------------------------------------
 Add-on: Dashy
 Dashy is an open source, highly customizable, easy to use, privacy-respecting dashboard app
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.0
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
yarn run v1.22.19
$ node server

Checking config file against schema...
✔️ Config file is valid, no issues found

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Welcome to Dashy! 🚀                                                      ┃
┃ Your new dashboard is now up and running at http://172.30.33.11:4000      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛



Using Dashy V-3.1.1. Update Check Complete
✅ Dashy is Up-to-Date

**Comment by BenoitAnastay** [comment]
My bad, changes weren't pushed to the main repository

**Comment by mbobbar** [comment]
All working, thanks for fixing it up!
